Updated Readme file
wallyax/wax-dev pull request #3
Opened 2024-06-21 16:00 UTC by fsthangaraj

2024-06-24 04:39 UTC, shritt requested changes

2024-06-24 04:39 UTC, shritt commented on README.md
> +title:  'Wax-Dev',
Let us change this too WAX Accessibility Issues

2024-06-24 05:11 UTC, fsthangaraj commented on README.md
> +title:  'Wax-Dev',
Renamed the panel name to WAX Accessibility Issues

2024-07-17 05:45 UTC, shritt approved these changes

2024-07-17 06:38 UTC, merged